# Generated by Django 4.2.14 on 2025-06-10 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_sector_threat_remove_iot_device_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='name',
        ),
        migrations.AddField(
            model_name='threat',
            name='attack_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='threat_Level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iot_device',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='iot_device',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Associated_Sector', to='iot.sector'),
        ),
        migrations.AlterField(
            model_name='iot_device',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Associated_Threat_Level', to='iot.threat'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
