# Generated by Django 4.2.14 on 2025-06-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_remove_threat_name_threat_attack_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic_of_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='threat',
            name='devices',
            field=models.ManyToManyField(related_name='threats', to='iot.iot_device'),
        ),
        migrations.CreateModel(
            name='Threat_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='iot.threat')),
                ('topic_of_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_details', to='iot.topic_of_details')),
            ],
        ),
    ]
