# Generated by Django 4.2.14 on 2025-06-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_topic_of_details_threat_devices_threat_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic_of_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Threat_Details',
        ),
        migrations.DeleteModel(
            name='Topic_of_details',
        ),
        migrations.AddField(
            model_name='threat_detail',
            name='topic_of_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.topic_of_detail'),
        ),
        migrations.AddField(
            model_name='threat',
            name='Threat_Detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iot.threat_detail'),
        ),
    ]
