# Generated by Django 4.2.14 on 2025-06-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_threat_detail_topic_of_detail_delete_threat_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat_detail',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
