# Generated by Django 4.2.14 on 2025-06-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_alter_threat_detail_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot_device',
            name='threat',
        ),
    ]
