# Generated by Django 4.2.14 on 2025-06-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_remove_iot_device_sector_iot_device_sector'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic_of_detail',
            new_name='Threat_Info_Category',
        ),
        migrations.RenameField(
            model_name='threat_detail',
            old_name='topic_of_details',
            new_name='threat_Info_Category',
        ),
    ]
