# Generated by Django 4.2.21 on 2025-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_remove_threat_threat_detail_threat_threat_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
