# Generated by Django 4.2.21 on 2025-06-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_alter_iot_device_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat',
            name='Threat_Detail',
        ),
        migrations.AddField(
            model_name='threat_detail',
            name='Threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_details', to='iot.threat'),
        ),
    ]
