# Generated by Django 4.2.21 on 2025-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_remove_threat_threat_detail_threat_detail_threat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='threat_info_category',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
