# Generated by Django 4.2.14 on 2025-07-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_alter_iot_device_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot_device',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='threat',
            name='attack_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='threat',
            name='threat_Level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='threat_detail',
            name='Threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_details', to='iot.threat'),
        ),
        migrations.AlterField(
            model_name='threat_detail',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='threat_detail',
            name='threat_Info_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.threat_info_category'),
        ),
        migrations.AlterField(
            model_name='threat_info_category',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='threat_info_category',
            name='topic',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
