# Generated by Django 4.2.21 on 2025-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_alter_iot_device_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='CVE_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
