# Generated by Django 4.2.14 on 2025-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_threat_cve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
