# Generated by Django 4.2.14 on 2025-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_alter_threat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat_info_category',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
